@api_url = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjkxYWNjMGI4YmY5N2U3MzFjMGIzMjMxIn0sImlhdCI6MTc2MzcwODY0MCwiZXhwIjoxNzYzNzEyMjQwfQ.YIIQ2xH1MRjZOZNaCLSwTE4_NnSQHwrC_VLEDslCwpk

### Registrar un nuevo usuario
POST {{api_url}}/auth/register
Content-Type: application/json

{
    "nombre": "arleth",
    "email": "arleth@gmail.com",
    "password": "kira"
}

### Iniciar sesión un usuario
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "email": "arleth@gmail.com",
    "password": "kira"
}

### CATEGORIAS
### Obtener todas las categorías
GET {{api_url}}/categorias

### Crear una nueva categoría
POST {{api_url}}/categorias
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Semana de la cultura"
}

### Actualizar una categoría
PUT {{api_url}}/categorias/69200f554b1cd63fe8bafac0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Cultura"
}

### Eliminar una categoría
DELETE {{api_url}}/categorias/69200f554b1cd63fe8bafac0
Authorization: Bearer {{token}}

### PUBLICACIONES
### Obtener todas las publicaciones
GET {{api_url}}/publicaciones?limit=3&page=5

### Obtener las publicaciones destacadas
GET {{api_url}}/publicaciones/destacadas

### Obtener publicaciones destacadas por ID.
GET {{api_url}}/publicaciones/691acea18bf97e731c0b324d

### Crear una nueva publicación
POST {{api_url}}/publicaciones
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "test",
    "resumen": "test",
    "contenido_completo": "test",
    "autor": "test",
    "es_destacado": true,
    "tipo": "Noticia",
    "categoria": "691acd0d8bf97e731c0b323a",
    "fecha_evento_inicio": "2021-01-01",
    "fecha_evento_cierre": "2021-01-01"
}

### Actualizar una publicación
PUT {{api_url}}/publicaciones/691acea18bf97e731c0b324d
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "Semana de la cultura"
}

### Eliminar una publication
DELETE {{api_url}}/publicaciones/691acea18bf97e731c0b324d
Authorization: Bearer {{token}}

### GACETAS
### Obtener todas las gacetas
GET {{api_url}}/gacetas

### Crear una nueva gaceta
POST {{api_url}}/gacetas
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "test",
    "mes": 1,
    "ano": 2021,
    "url_pdf": "test"
}

### Eliminar una gaceta
DELETE {{api_url}}/gacetas/66441e4a704788698edad0b7
Authorization: Bearer {{token}}

### UPLOAD
### Actualizar una gaceta
POST {{api_url}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

test
------WebKitFormBoundary7MA4YWxkTrZu0gW--
